# Generated by Django 3.2.7 on 2022-09-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220916_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
